### ISSUE TITLE
doesnt work on ubuntu 18

### ISSUE THREAD

**Issue by imranabyss** [NICHOLAS85/z-a-linkbin#1]
This annex fails to create symbolic links for binary files on Ubuntu 18. The `lbin` command seems to do nothing.

**Comment by NICHOLAS85** [comment]
Could you provide the zinit ice and invocation so I can try to reproduce your issue? Thanks!

**Comment by imranabyss** [comment]
> Could you provide the zinit ice and invocation so I can try to reproduce your issue? Thanks!

```zsh
zt 0c light-mode binary from'gh-r' lman lbin for \
    bpick'*linux64*' \
        zyedidia/micro \
    lbin'%PLUGIN%*/%PLUGIN%' atclone'mv -f **/*.zsh _bat' atpull'%atclone' \
        @sharkdp/bat \
        @sharkdp/hyperfine \
        @sharkdp/fd
zt 0c light-mode binary for \
    lbin'bin/*' \
        laggardkernel/git-ignore \
    lbin'*/lsd' from'gh-r' atclone'wget -q https://raw.githubusercontent.com/Peltoche/lsd/master/doc/lsd.md -O lsd.1.ronn; ronn lsd.1.ronn' atpull'%atclone' lman \
        Peltoche/lsd \
    lbin'nnn* -> nnn' from'gh-r' bpick'*nerd*' atclone'wget -q https://raw.githubusercontent.com/jarun/nnn/master/nnn.1' atpull'%atclone' lman  \
        jarun/nnn
zt 0c light-mode null for \
    lbin'*d.sh;*n.sh' \
        bkw777/notify-send.sh \
    lbin'antidot* -> antidot' from'gh-r' atclone'./**/antidot* update 1>/dev/null' atpull'%atclone' \
        doron-cohen/antidot \
    lbin'git-open' \
        paulirish/git-open \
    lbin'*/delta' from'gh-r' patch"${pchf}/%PLUGIN%.patch" \
        dandavison/delta \
    lbin'rm-trash/rm-trash' lman patch"${pchf}/%PLUGIN%.patch" atload'alias rm=rm-trash' reset \
        nateshmbhat/rm-trash \
    lbin'fzf' from'gh-r' atclone'wget -q https://raw.githubusercontent.com/junegunn/fzf/master/man/man1/fzf.1' atpull'%atclone' lman \
        junegunn/fzf
```

@NICHOLAS85 These are the packages I'm trying to install. It passes `ziextract` stage correctly, but does not symlink binaries to /bin or /usr/bin directory. I have tested this on Manjaro OS, and it created hard-links after `ziextract` in that OS correctly, but not on Ubuntu.

**Comment by NICHOLAS85** [comment]
Do the binaries appear in `$ZPFX/bin`? That should be `$HOME/.zinit/polaris/bin` in default Zinit installations. It makes sense they wouldn't appear under /bin or /usr/bin as linkbin does not link the binaries to those locations

**Comment by imranabyss** [comment]
> Do the binaries appear in `$ZPFX/bin`? That should be `$HOME/.zinit/polaris/bin` in default Zinit installations. It makes sense they wouldn't appear under /bin or /usr/bin as linkbin does not link the binaries to those locations

No the binaries do not appear in the `$ZPFX/bin` for me, which is the default `$HOME/.zinit/polaris/bin` directory. That directory is empty. Makes sense that it doesn't link binaries to /bin or /usr/bin. What I meant to say was the message to confirm lbin created a hard-link for some binary does not appear during install/update.

**Comment by NICHOLAS85** [comment]
Interesting, could you share your complete zshrc as well (if that's reasonable of course). Are there any error messages that appear upon loading the annex or while using lbin with other plugins?

**Comment by imranabyss** [comment]
> Interesting, could you share your complete zshrc as well (if that's reasonable of course). Are there any error messages that appear upon loading the annex or while using lbin with other plugins?

Sure thing, my zshrc file can be downloaded from [here](https://files.imranc.io/zinit/.zshrc). It's very similar to your setup posted on zdharma/zinit-configs. And no, there are no error messages upon loading the annex or using lbin. Just the lack of the confirmation message saying lbin created hard link for some binary.

**Comment by NICHOLAS85** [comment]
When you say "some binary" does that mean it works in some cases and with other it does not? If so could you give an example of a plugin it doesn't work with. If you mean it's not working at all I'll try to see what's going on.

**Comment by imranabyss** [comment]
> When you say "some binary" does that mean it works in some cases and with other it does not? If so could you give an example of a plugin it doesn't work with. If you mean it's not working at all I'll try to see what's going on.

No this is for all cases where lbin is used. It fails for all of those.

**Comment by NICHOLAS85** [comment]
Does it function when something is passed to the ice? Ex `lbin'fzf'`

**Comment by NICHOLAS85** [comment]
Okay I am able to reproduce the issue, I believe it may be related to your zsh version (different behavior from recent versions). I'll see if I can fix the issue.

**Comment by NICHOLAS85** [comment]
Go ahead and update z-a-linkbin and let me know if the issue still persist

**Comment by imranabyss** [comment]
> Go ahead and update z-a-linkbin and let me know if the issue still persist

Thanks so much @NICHOLAS85 for your quick response! I will update and get back to you within 24 hours if the issue still persists or not.

**Comment by imrancio** [comment]
I can confirm this is now fixed.
