### ISSUE TITLE
does not ensure `polaris/bin` dir exists

### ISSUE THREAD

**Issue by jankatins** [NICHOLAS85/z-a-linkbin#3]
see this session:

```
Downloading bigH/git-fuzzy…
Cloning into '/Users/jankatins/.local/share/zinit/plugins/bigH---git-fuzzy'...
⠸ ███████████ OBJ: 100, PACK: 450/450, COMPR: 100%, REC: 100%, RES: 100%
ln: /Users/jankatins/.local/share/zinit/polaris/bin/git-fuzzy: No such file or directory
linkbin annex: Something went wrong creating the git-fuzzy link

[11:26:32] [1] ✗  ls -la /Users/jankatins/.local/share/zinit/polaris/
total 0
drwxr-xr-x   3 jankatins  staff   96 Jun 13 11:16 .
drwx--xr-x   8 jankatins  staff  256 Jun 13 11:16 ..
drwxr-xr-x  11 jankatins  staff  352 Jun 13 11:16 man
```

**Comment by NICHOLAS85** [comment]
I've opted for creating `$ZPFX/bin` if it doesn't exist when the linkbin plugin loads. Let me know if this still gives you trouble.

**Comment by jankatins** [comment]
Will you keep this repo or will this be moved to https://github.com/zdharma-continuum/zinit-annex-binary-symlink?

**Comment by NICHOLAS85** [comment]
I'll likely make a pr there for the latest changes so the two repos match feature-wise.

**Comment by jankatins** [comment]
Seems this is now also fixed in https://github.com/zdharma-continuum/zinit-annex-binary-symlink/pull/6 -> closing as fixed

Thank you!
